
# Default: docker/robotshop/image:latest
image:
  repo: robotshop
  version: latest
  pullPolicy: IfNotPresent

# Pod Security Policy
psp:
  enabled: false


cart: {}

catalogue: {}

dispatch: {}

mongodb: {}

mysql: {}

payment:
  gateway: null
 

rabbitmq: {}

ratings: {}

redis:
  storageClassName: gp2

shipping: {}

user: {}

web: {}
